import { StaffMember, CommunityEvent, RewardItem } from './types';

export const INITIAL_STAFF_MEMBERS: StaffMember[] = [
  {
    id: 'staff-1',
    name: '田中 恵子',
    nickname: 'けいこさん',
    role: '子育て見守りボランティア',
    avatarUrl: '/src/assets/images/staff_keiko_obasan_1790226336932.jpg',
    comment: '今日はお絵描き・折り紙コーナーにいます！抱っこの交代もお気軽にどうぞ😊',
    specialty: '絵本読み聞かせ・手遊び',
    isPresentToday: true,
    presentStartTime: '10:00〜16:00',
  },
  {
    id: 'staff-2',
    name: '佐藤 大樹',
    nickname: 'だいき先生',
    role: '保育士・広場サポーター',
    avatarUrl: '/src/assets/images/staff_daiki_san_1790226354234.jpg',
    comment: '元気いっぱい走れるマット運動スペースを見守っています！何でも聞いてね。',
    specialty: 'からだあそび・工作',
    isPresentToday: true,
    presentStartTime: '09:30〜17:00',
  },
  {
    id: 'staff-3',
    name: '小林 美智子',
    nickname: 'みっちゃん',
    role: '助産師・育児相談員',
    avatarUrl: '',
    comment: '授乳やおむつ替え、離乳食のちょっとした悩みなど、いつでも声かけてくださいね。',
    specialty: '赤ちゃんの健康・授乳相談',
    isPresentToday: true,
    presentStartTime: '11:00〜15:00',
  },
  {
    id: 'staff-4',
    name: '高橋 健一',
    nickname: 'けんじいちゃん',
    role: '地域木育ボランティア',
    avatarUrl: '',
    comment: '木のつみき・パズルで一緒に遊ぼう！修理や遊び方のコツも教えるよ。',
    specialty: '木のおもちゃ・昔あそび',
    isPresentToday: false,
    presentStartTime: '土日のみ',
  },
  {
    id: 'staff-5',
    name: '松本 彩香',
    nickname: 'あやかさん',
    role: '子育てママサポーター',
    avatarUrl: '',
    comment: '私自身も2児のママです！気軽におしゃべりしてリフレッシュしましょう♪',
    specialty: 'おしゃべり交流・プレママ相談',
    isPresentToday: false,
    presentStartTime: '平日午後',
  },
];

export const INITIAL_EVENTS: CommunityEvent[] = [
  {
    id: 'event-1',
    title: 'みんなあつまれ！大型えほん＆てあそび会',
    date: '2026-09-24', // Today
    time: '11:00〜11:40',
    location: 'ぽかぽか広場 プレイルーム中央',
    targetAge: '0歳〜3歳のお子様と保護者',
    fee: '無料',
    capacity: 15,
    currentBookings: 11,
    description: '季節の大型絵本や、親子でふれあえる楽しい手遊びうたをボランティアスタッフと一緒に楽しみます。途中参加・退室も自由ですのでお気軽にお越しください。',
    imageUrl: '/src/assets/images/event_ehon_story_1790226373856.jpg',
    isFeatured: true,
    tags: ['絵本', '手遊び', '0〜3歳', '予約不要'],
  },
  {
    id: 'event-2',
    title: '助産師みっちゃんのプチ育児・授乳相談カフェ',
    date: '2026-09-24', // Today
    time: '13:30〜15:00',
    location: '相談コーナー（畳スペース）',
    targetAge: '0歳児の保護者・プレママ',
    fee: '無料',
    capacity: 8,
    currentBookings: 6,
    description: '助産師スタッフに、赤ちゃんの体重のことや授乳リズム、離乳食の進め方などを個別にゆったり相談できる温かいサロンです。ハーブティーをご用意しています。',
    isFeatured: true,
    tags: ['助産師', '育児相談', '0歳児', '個別対応'],
  },
  {
    id: 'event-3',
    title: '新聞紙ビリビリ！わくわく感覚あそび',
    date: '2026-09-25', // Tomorrow
    time: '10:30〜11:30',
    location: '多目的アクティビティ室',
    targetAge: '1歳〜5歳',
    fee: '無料',
    capacity: 20,
    currentBookings: 14,
    description: '新聞紙を破いたり、丸めてボールにしたり、紙吹雪シャワーを浴びたり！お家ではなかなかできないダイナミックな感覚遊びをおもいっきり体験できます。',
    imageUrl: '/src/assets/images/hero_play_lounge_1790226320736.jpg',
    isFeatured: false,
    tags: ['感覚あそび', '1〜5歳', '汚れない', '運動'],
  },
  {
    id: 'event-4',
    title: '【週末スペシャル】木のおもちゃフェスタ＆けん玉教室',
    date: '2026-09-27', // Weekend
    time: '10:00〜12:00 / 14:00〜16:00',
    location: 'ぽかぽか広場 全館',
    targetAge: '未就学児〜小学生',
    fee: '無料',
    capacity: 30,
    currentBookings: 22,
    description: '地域の木工職人さん手作りの積み木やコマ、けん玉、からくりおもちゃが大集合！名人のけんじいちゃんがコツを優しく伝授してくれます。',
    isFeatured: true,
    tags: ['週末イベント', '木育', '全年齢', 'おみやげあり'],
  },
  {
    id: 'event-5',
    title: 'パパと一緒に楽しむふれあい体操＆ストレッチ',
    date: '2026-09-27', // Weekend
    time: '13:00〜14:00',
    location: 'マットエリア',
    targetAge: '首すわり〜未就学児とパパ（ママの参加も歓迎）',
    fee: '無料',
    capacity: 12,
    currentBookings: 8,
    description: '休日のお出かけにぴったり！パパとお子様が体を動かしながら笑顔になれるふれあい体操。日頃の抱っこ疲れをほぐすパパ向けストレッチタイムもあります。',
    isFeatured: false,
    tags: ['パパ歓迎', '体操', '週末', 'リフレッシュ'],
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'reward-1',
    title: '駄菓子コーナー おやつ券',
    requiredPoints: 30,
    description: '受付横の「だがし屋さん」から、好きなお菓子を1つ選べる引換チケットです。',
    category: 'snack',
    iconName: 'Cookie',
    badge: '1番人気',
  },
  {
    id: 'reward-2',
    title: 'ぽかぽかカプセル ガチャチケット',
    requiredPoints: 50,
    description: '受付にある特大ガチャガチャが1回まわせます！可愛い木製バッジや動物消しゴムが当たるよ。',
    category: 'gacha',
    iconName: 'Sparkles',
    badge: '子どもに大好評',
  },
  {
    id: 'reward-3',
    title: '無添加 ミニソフトクリーム券',
    requiredPoints: 70,
    description: '施設カフェ「ぽかぽか茶房」で使える、地元牧場のミニソフトクリーム（カップ）引換券です。',
    category: 'snack',
    iconName: 'IceCream',
    badge: 'おやつタイムに',
  },
  {
    id: 'reward-4',
    title: '木工工作キット（動物ミニカー）',
    requiredPoints: 100,
    description: 'お家で組み立てられる天然木のミニカー工作キット。色えんぴつで好きな模様を描けます。',
    category: 'gift',
    iconName: 'Gift',
    badge: '記念ギフト',
  },
];
